### ISSUE TITLE
WPS Office 并未同步到最新版本

### ISSUE THREAD

**Issue by xrgzs** [EdgelessPE/edgeless-bot#104]
目前 Edgeless 插件的 WPS Office 停留在了 v11.1.0.15319 版本，爬虫脚本的直链已经被官方抛弃

最新版本的API信息如下：

GET https://www.wps.cn/platformUrls

返回的JSON数据里面包含所有平台的最新安装包直链

Windows 平台最新版本安装包的 JSON 路径：

下载地址：JSON.productDetail.productButtonUrl
版本号：JSON.productDetail.productVcode

下载地址：JSON.productList[0].productButtonUrl
版本号：JSON.productList[0].productVcode

**Comment by Cnotech** [comment]
感谢反馈，已修复
