### ISSUE TITLE
增加蓝奏网盘解析器

### ISSUE THREAD

**Issue by xrgzs** [EdgelessPE/edgeless-bot#131]
需要支持解析 带密码 和 不带密码 的 文件类型分享 和 目录类型分享

**Comment by Cnotech** [comment]
@xrgzs 正在写lanzou的api，可以帮忙找一个带密码的分享链接嘛，我的账号登不上去了🤨

**Comment by Cnotech** [comment]
尝试写了一下，解析出来的直链会400...吴语了，找不到问题在哪

https://github.com/Cnotech/lanzou-api

**Comment by xrgzs** [comment]
> https://github.com/Cnotech/lanzou-api

貌似直链解析部分的代码没提交？好像只有爬取分享链接部分的

**Comment by xrgzs** [comment]
我在想能不能只负责爬取到文件的最终分享链接，直链解析交由其它接口处理，顺便避免IP block问题

**Comment by Cnotech** [comment]
确实代码没push上来，我回去再推送一下；最好不要再引入额外的服务依赖了吧（实在解决不了除外

IP Block可以参考php版本的，加个X-FORWARDED-FOR头就行： https://github.com/hanximeng/LanzouAPI/blob/b4958b4949e9acd9a6513a1c5b51ea1739ecb2e1/index.php#L166

**Comment by Cnotech** [comment]
已经推送了，有兴趣可以看看

**Comment by xrgzs** [comment]
> 尝试写了一下，解析出来的直链会400...吴语了，找不到问题在哪
> 
> https://github.com/Cnotech/lanzou-api

找到问题了，在请求 ajaxm.php 的时候 referer 头拼错了

https://github.com/Cnotech/lanzou-api/pull/1

**Comment by Cnotech** [comment]
已添加一个简单的蓝奏解析器：https://wiki.edgeless.top/bot/templates/resolver/lanzou.html ，并且本地测试了下 RunningCheeseChrome 的任务可以正常执行
