### ISSUE TITLE
增加GitHub模板解析时使用Pre_release版本的参数

### ISSUE THREAD

**Issue by xrgzs** [EdgelessPE/edgeless-bot#138]
目前在使用过程中发现GitHub模板解析时只会使用latest版本，希望能够增加参数支持使用Pre_release版本，不要跳过Pre_release

**Comment by Cnotech** [comment]
当时做过滤 pre 的原因是 Edgeless 不希望将非正式版的软件分发给用户，因为这通常来说是没有必要的（除非像 ChromeBeta ChromeDev 这样新开一个任务名）；目前是遇到什么问题导致需要支持 pre_release 呢？

**Comment by xrgzs** [comment]
https://github.com/rizonesoft/Notepad3/releases
