### ISSUE TITLE
在编写脚本时避免使用绝对路径

### ISSUE THREAD

**Issue by xrgzs** [EdgelessPE/edgeless-bot#140]
Edgeless插件大量使用了X:\User\Default、%programfiles%\Edgeless 等较为绝对的路径，不方便在桌面环境、A/S双用户PE下使用，希望能够规范一下对路径的使用

**Comment by Cnotech** [comment]
在脚本里面写死Edgeless文件夹的路径是为了防止被其他项目滥用插件包，目前来说是有必要的，这个问题在下一代nep规范中得到了解决（已经在开发中，进度约85%）
default用户的问题也是类似，暂时没法对存量的插件包做逐一改造

**Comment by Cnotech** [comment]
https://github.com/EdgelessPE/ept

可以关注一下这个仓库的更新
